/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uam.airport.vuelos;

import com.uam.Hangar69.AeroNaves.Aviones;
import com.uam.Hangar69.AeroNaves.RegistrarAeronaves;
import java.util.Calendar;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kenneth
 */


public class GUIRegistroVuelos extends javax.swing.JFrame{
    
    RegistrarAeronaves registroAeronaves;
    RegistroVuelos listaVuelos;
    String []Destinos = {"SJO - San Jose","PTR - Orotina","MIA - Miami"};
    String horaLlegada;
    String horaSalida;
    Calendar salida;
    Calendar llegada;
    String duracion;
    String codigoVuelo;
    int dias,horas,minutos;

    /**
     * Creates new form GUIRegistroVuelos
     */
    public GUIRegistroVuelos(RegistrarAeronaves registroAeronaves,RegistroVuelos listaVuelos) {
        this.registroAeronaves=registroAeronaves;
        this.listaVuelos=listaVuelos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxHoraSalida = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxLlegada = new javax.swing.JComboBox<>();
        jComboBoxMinutosSalida = new javax.swing.JComboBox<>();
        jComboBoxMinutosLlegada = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jDateChooserDateArrive = new com.toedter.calendar.JDateChooser();
        jDateChooserDateOut = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxOrigen = new javax.swing.JComboBox<>();
        jTextFieldduracion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPiloto = new javax.swing.JTextField();
        jComboBoxDestinos = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPrecioTurista = new javax.swing.JTextField();
        jTextFieldPRecioVIP = new javax.swing.JTextField();

        jLabel1.setText("Hora salida :");

        jLabel3.setText("Destino :");

        jComboBoxHoraSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jComboBoxHoraSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHoraSalidaActionPerformed(evt);
            }
        });
        jComboBoxHoraSalida.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxHoraSalidaPropertyChange(evt);
            }
        });

        jLabel4.setText("Origen :");

        jLabel2.setText("Hora llegada :");

        jLabel5.setText("Duración vuelo :");

        jComboBoxLlegada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jComboBoxLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLlegadaActionPerformed(evt);
            }
        });
        jComboBoxLlegada.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxLlegadaPropertyChange(evt);
            }
        });

        jComboBoxMinutosSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "10", "15", "20", "25", "30", "35", "40", "45" }));
        jComboBoxMinutosSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMinutosSalidaActionPerformed(evt);
            }
        });

        jComboBoxMinutosLlegada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "10", "15", "20", "25", "30", "35", "40", "45", "60" }));

        jLabel6.setText("Día Salida :");

        jLabel7.setText("Día llegada :");

        jComboBoxOrigen.setSelectedItem(jComboBoxOrigen);
        jComboBoxOrigen.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxOrigenPropertyChange(evt);
            }
        });

        jTextFieldduracion.setEditable(false);
        jTextFieldduracion.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextFieldduracionPropertyChange(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Piloto :");

        jComboBoxDestinos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxDestinosPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jDateChooserDateOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jDateChooserDateArrive, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextFieldduracion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxLlegada, 0, 49, Short.MAX_VALUE)
                                    .addComponent(jComboBoxHoraSalida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxMinutosSalida, 0, 50, Short.MAX_VALUE)
                                    .addComponent(jComboBoxMinutosLlegada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxDestinos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPiloto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.Alignment.LEADING, 0, 210, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxDestinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxMinutosSalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jComboBoxMinutosLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jDateChooserDateArrive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel6))
                            .addComponent(jDateChooserDateOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldduracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Matricula", "Avion", "Espacios", "Primera Clase", "Activo"
            }
        ));
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setText("Precio Clase Turista :");

        jLabel10.setText("Precio Primera Clase :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(15, 15, 15)
                .addComponent(jTextFieldPrecioTurista, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addComponent(jTextFieldPRecioVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldPrecioTurista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldPRecioVIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 477, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxHoraSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHoraSalidaActionPerformed
        
        
        
        
        
        
    }//GEN-LAST:event_jComboBoxHoraSalidaActionPerformed

    private void jComboBoxLlegadaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxLlegadaPropertyChange
        // TODO add your handling code here:
  
    }//GEN-LAST:event_jComboBoxLlegadaPropertyChange

    private void jComboBoxHoraSalidaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxHoraSalidaPropertyChange

        
        
        
    }//GEN-LAST:event_jComboBoxHoraSalidaPropertyChange

    private void jComboBoxLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLlegadaActionPerformed

    }//GEN-LAST:event_jComboBoxLlegadaActionPerformed

    private void jComboBoxMinutosSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMinutosSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMinutosSalidaActionPerformed

    private void jComboBoxDestinosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxDestinosPropertyChange
        // TODO add your handling code here:
        
        jComboBoxDestinos.addItem(Destinos[0]);
        jComboBoxDestinos.addItem(Destinos[1]);
        jComboBoxDestinos.addItem(Destinos[2]);
        
        
    }//GEN-LAST:event_jComboBoxDestinosPropertyChange

    private void jComboBoxOrigenPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxOrigenPropertyChange
        // TODO add your handling code here:
        
        
        jComboBoxOrigen.addItem(Destinos[0]);
        jComboBoxOrigen.addItem(Destinos[1]);
        jComboBoxOrigen.addItem(Destinos[2]);
        

        
        
        
        
        
    }//GEN-LAST:event_jComboBoxOrigenPropertyChange

    private void jTextFieldduracionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextFieldduracionPropertyChange
        // TODO add your handling code here:
        

        
        
        
    }//GEN-LAST:event_jTextFieldduracionPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
     try {
                mostrar();

                duracionVuelo();
                if(isCorrect()){
                 jTextFieldduracion.setText(duracion);
                 
                }else{
                    JOptionPane.showMessageDialog(null, "Ha ingresado una hora inferior a la hora de salida.");
                }
                
                    

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
    // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_jTable1PropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
             if(validadorGuardar()){
     // Con JCombobox
        Object seleccion = JOptionPane.showInputDialog(
           null,
           "Seleccione Cantidad de dias a repetir ruta :",
           "Selector de opciones",
           JOptionPane.QUESTION_MESSAGE,
           null,  // null para icono defecto
           new Object[] { "1 día", "2 días", "7 días" }, 
           "opcion 1");

        System.out.println("El usuario ha elegido "+seleccion);
     if(seleccion=="1 día"){
         
     generarCodigoVuelo();
     duracionVuelo();
     Aviones nAvion=registroAeronaves.getAvion(jTable1.getSelectedRow());
     Aviones nAvionClonado=new Aviones(nAvion);

     
     Vuelos nuevoVuelo = new Vuelos(nAvionClonado,jDateChooserDateOut.getCalendar(), jDateChooserDateArrive.getCalendar(),jComboBoxDestinos.getSelectedItem().toString(),jComboBoxOrigen.getSelectedItem().toString(),dias,horas,minutos);
     nuevoVuelo.setPiloto(jTextFieldPiloto.getText());
     nuevoVuelo.setPrecioPrimera(Integer.parseInt(jTextFieldPRecioVIP.getText()));
     nuevoVuelo.setPrecioTurista(Integer.parseInt(jTextFieldPrecioTurista.getText()));
     nuevoVuelo.setHorasLlegada(this.horaLlegada);
     nuevoVuelo.setHorasSalida(this.horaSalida);
     nuevoVuelo.setCodigoVuelo(this.codigoVuelo);
     nuevoVuelo.setDuracion(duracion);
     listaVuelos.add(nuevoVuelo);
     
     JOptionPane.showMessageDialog(null,"Ha programado 1 ruta por 1 día" );
         
     }else if(seleccion=="2 días"){
         
     for(int x=0;x<2;x++){
    generarCodigoVuelo();
     duracionVuelo();
     Aviones nAvion=registroAeronaves.getAvion(jTable1.getSelectedRow());
     Aviones nAvionClonado=new Aviones(nAvion);
     
     Vuelos nuevoVuelo = new Vuelos(nAvionClonado,jDateChooserDateOut.getCalendar(), jDateChooserDateArrive.getCalendar(),jComboBoxDestinos.getSelectedItem().toString(),jComboBoxOrigen.getSelectedItem().toString(),dias,horas,minutos);
     nuevoVuelo.setPiloto(jTextFieldPiloto.getText());
     nuevoVuelo.setPrecioPrimera(Integer.parseInt(jTextFieldPRecioVIP.getText()));
     nuevoVuelo.setPrecioTurista(Integer.parseInt(jTextFieldPrecioTurista.getText()));
     nuevoVuelo.setHorasLlegada(this.horaLlegada);
     nuevoVuelo.setHorasSalida(this.horaSalida);
     nuevoVuelo.setCodigoVuelo(this.codigoVuelo);
     nuevoVuelo.setDuracion(duracion);
     llegada.add(Calendar.DAY_OF_YEAR, x);
     salida.add(Calendar.DAY_OF_YEAR, x);
     nuevoVuelo.setLlegada(llegada);
     nuevoVuelo.setSalida(salida);
     listaVuelos.add(nuevoVuelo);
             
         }
         
     JOptionPane.showMessageDialog(null,"Ha programado 1 ruta por 2 días" );
     }else if(seleccion=="7 días"){
     for(int x=0;x<7;x++){
     generarCodigoVuelo();
     duracionVuelo();
     Aviones nAvion=registroAeronaves.getAvion(jTable1.getSelectedRow());
     Aviones nAvionClonado=new Aviones(nAvion);

     
     Vuelos nuevoVuelo = new Vuelos(nAvionClonado,jDateChooserDateOut.getCalendar(), jDateChooserDateArrive.getCalendar(),jComboBoxDestinos.getSelectedItem().toString(),jComboBoxOrigen.getSelectedItem().toString(),dias,horas,minutos);
     nuevoVuelo.setPiloto(jTextFieldPiloto.getText());
     nuevoVuelo.setPrecioPrimera(Integer.parseInt(jTextFieldPRecioVIP.getText()));
     nuevoVuelo.setPrecioTurista(Integer.parseInt(jTextFieldPrecioTurista.getText()));
     nuevoVuelo.setHorasLlegada(this.horaLlegada);
     nuevoVuelo.setHorasSalida(this.horaSalida);
     nuevoVuelo.setCodigoVuelo(this.codigoVuelo);
     nuevoVuelo.setDuracion(duracion);
     llegada.add(Calendar.DAY_OF_YEAR, x);
     salida.add(Calendar.DAY_OF_YEAR, x);
     nuevoVuelo.setLlegada(llegada);
     nuevoVuelo.setSalida(salida);
     listaVuelos.add(nuevoVuelo);
             
         }     JOptionPane.showMessageDialog(null,"Ha programado 1 ruta por 7 días" );
     }
     }else{
     JOptionPane.showMessageDialog(null, "Debe de completar todos los datos");
     }
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Debe de seleccionar un avion");
        }
              

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRegistroVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRegistroVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRegistroVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRegistroVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxDestinos;
    private javax.swing.JComboBox<String> jComboBoxHoraSalida;
    private javax.swing.JComboBox<String> jComboBoxLlegada;
    private javax.swing.JComboBox<String> jComboBoxMinutosLlegada;
    private javax.swing.JComboBox<String> jComboBoxMinutosSalida;
    private javax.swing.JComboBox<String> jComboBoxOrigen;
    private com.toedter.calendar.JDateChooser jDateChooserDateArrive;
    private com.toedter.calendar.JDateChooser jDateChooserDateOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldPRecioVIP;
    private javax.swing.JTextField jTextFieldPiloto;
    private javax.swing.JTextField jTextFieldPrecioTurista;
    private javax.swing.JTextField jTextFieldduracion;
    // End of variables declaration//GEN-END:variables

public void duracionVuelo(){
    
    int tmpllegada;
    int tmpSalida;
    generarCodigoVuelo();

    
    
    this.llegada = jDateChooserDateArrive.getCalendar();
    this.salida = jDateChooserDateOut.getCalendar();
    this.llegada.set(Calendar.HOUR_OF_DAY, Integer.parseInt(jComboBoxLlegada.getSelectedItem().toString()));
    this.llegada.set(Calendar.MINUTE, Integer.parseInt(jComboBoxMinutosLlegada.getSelectedItem().toString()));
    this.salida.set(Calendar.HOUR_OF_DAY, Integer.parseInt(jComboBoxHoraSalida.getSelectedItem().toString()));
    this.salida.set(Calendar.MINUTE, Integer.parseInt(jComboBoxMinutosSalida.getSelectedItem().toString()));
    
    
    tmpllegada=llegada.get(Calendar.DAY_OF_YEAR)*24*60+llegada.get(Calendar.HOUR_OF_DAY)*60+llegada.get(Calendar.MINUTE);
    tmpSalida=salida.get(Calendar.DAY_OF_YEAR)*24*60+salida.get(Calendar.HOUR_OF_DAY)*60+salida.get(Calendar.MINUTE);
    
    this.dias=(tmpllegada-tmpSalida)/60/24;
    this.horas=(tmpllegada-tmpSalida)/60;
    this.minutos=(tmpllegada-tmpSalida)-this.horas*60;

    duracion = " Horas: "+this.horas+" Minutos: "+this.minutos;
    
    this.horaLlegada=jComboBoxLlegada.getSelectedItem().toString()+":"+jComboBoxMinutosLlegada.getSelectedItem().toString();
    this.horaSalida=jComboBoxHoraSalida.getSelectedItem().toString()+":"+jComboBoxMinutosSalida.getSelectedItem().toString();
}

  public void mostrar(){
    String matris[][] = new String[this.registroAeronaves.sizeAvion()][6];
    DefaultTableModel tModel = (DefaultTableModel)this.jTable1.getModel();
    
      for (int i = 0; i < registroAeronaves.sizeAvion(); i++) {
          matris[i][0]=registroAeronaves.getAvion(i).getNombre();
          matris[i][1]=registroAeronaves.getAvion(i).getMatricula();
          matris[i][2]=registroAeronaves.getAvion(i).getModelo();
          matris[i][3]=Integer.toString(registroAeronaves.getAvion(i).getCantidadAsientosDisponibles());
          matris[i][4]=Integer.toString(registroAeronaves.getAvion(i).getCantidadAsientosPrimeraClases());
          matris[i][5]=(Boolean.toString(registroAeronaves.getAvion(i).isActiva()));
          
      }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Nombre", "Matricula", "Avion", "Espacios", "Primera Clase", "Activo"
            }
        ));
      
    
} 
  
public void generarCodigoVuelo(){
    Random r = new Random();
    String[]L ={"A","B","C","D","E","X","Z"};
    codigoVuelo=L[r.nextInt(7)]+Integer.toString(r.nextInt(9))+L[r.nextInt(7)]+Integer.toString(r.nextInt(9))+L[r.nextInt(7)]+Integer.toString(r.nextInt(9));
}



public boolean isCorrect(){
        return this.dias>=0&&this.horas>=0&&this.minutos>=0;
}

@Override
public Object clone() throws CloneNotSupportedException {
    Aviones octClone = (Aviones)super.clone();
    return octClone;
}
/**
 * 
 * Valida si es el mismo origen y destino
 * @return 
 */
public boolean validador(){
    
    
    return jComboBoxDestinos.getSelectedIndex()!=jComboBoxOrigen.getSelectedIndex();
    
    
}

public boolean validadorGuardar(){
    if(validador()){
        if(isCorrect()&&jTextFieldPiloto.getText().isEmpty()==false&&jTextFieldPrecioTurista.getText().isEmpty()==false&&jTextFieldPRecioVIP.getText().isEmpty()==false){
        
        return true;
        }else{
            return false;
        }
    }else{
        JOptionPane.showMessageDialog(null, "Revise el destino y origen, no pueden ser iguales");
        return false;
    }
    
}




}





