/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uam.airport.Asientos;

import com.uam.Hangar69.AeroNaves.Aviones;
import com.uam.airport.Asientos.Asientos;
import com.uam.airport.vuelos.RegistroVuelos;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Kenneth
 */
public class GUiSelectAsientos extends javax.swing.JFrame {

    /**
     * Creates new form GUiSelectAsientos
     */
    
    
    
    Aviones avion;
    RegistroVuelos listaVuelos;
    int filas=0;
    int columnas=0;
    String codigoVuelo,nombre;
    
    
    
    
    public Asientos [][]botones ;
            
    public GUiSelectAsientos(RegistroVuelos ListaVuelos,Aviones nAvion,String pCodigoVuelo,String pNombre) {
        this.nombre =pNombre;
        this.codigoVuelo=pCodigoVuelo;
        this.avion = nAvion;
        this.listaVuelos =  ListaVuelos;
        
        initComponents();
        Crearasientos(nAvion);
        configuracionAsientos(nAvion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextFieldCodigo = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldCodigo.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(926, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        addAsientos();
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUiSelectAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUiSelectAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUiSelectAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUiSelectAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    public void configuracionAsientos(Aviones nAvion){
    int[][] pConfiguracionAsientos= nAvion.getConfiguracionAsientos2();
    
    for (int fila =0;fila < nAvion.getAsientosporFila();fila++){
    for (int Columna =0;Columna < nAvion.getAsientosFila1()+nAvion.getAsientosFila2()+nAvion.getAsientosFila3();Columna++){
        if(pConfiguracionAsientos[fila][Columna]==0){
            botones[fila][Columna].setBackground(Color.GRAY);
            botones[fila][Columna].setEnabled(false);
        }else if(pConfiguracionAsientos[fila][Columna]==2){
            botones[fila][Columna].setBackground(Color.BLUE);
        }else {
            botones[fila][Columna].setBackground(null);
        }
         
    }
    }
}
    
    public void Crearasientos(Aviones pAvion){
        jPanel1.removeAll();
        columnas=pAvion.getAsientosFila1()+pAvion.getAsientosFila2()+pAvion.getAsientosFila3();
        filas=pAvion.getAsientosporFila();
        
    botones = new Asientos[filas][columnas];
    int distanciaAsientos=65;
    int distanciaTotal=0;
    int pasillo=0;
    
    for (int fila =0;fila < this.filas;fila++){
     distanciaTotal=0;
    for (int Columna =0;Columna < this.columnas;Columna++){
        if(Columna==pAvion.getAsientosFila1()||Columna==pAvion.getAsientosFila1()+pAvion.getAsientosFila2()||Columna==pAvion.getAsientosFila1()+pAvion.getAsientosFila2()+pAvion.getAsientosFila3()){
            pasillo=20;
        }else{
            pasillo=0;
        }
        distanciaTotal=distanciaTotal+distanciaAsientos+pasillo;
        
       botones[fila][Columna] =new Asientos(distanciaTotal,25 *fila, 60, 25);
       botones[fila][Columna].SetNombre(fila,Columna);
       jPanel1.add(botones[fila][Columna]);
       

    }
    }
    
    
    
}
    
   public void addAsientos(){
    int[][]array=listaVuelos.getbyCodigo(codigoVuelo).getAviondelVuelo().getConfiguracionAsientos2();
    for (int fila =0;fila < this.filas;fila++){
    for (int Columna =0;Columna < this.columnas;Columna++){
        if(botones[fila][Columna].getBackground()==Color.YELLOW){
            AsientosReservados nuevoAsientoReservado = new AsientosReservados(nombre, botones[fila][Columna].getText());
            
            JOptionPane.showInputDialog(Boolean.toString(listaVuelos.getbyCodigo(codigoVuelo).isEmptyAsientosReservados()));
            listaVuelos.getbyCodigo(codigoVuelo).addAsientosReservados(nuevoAsientoReservado);
            array[fila][Columna]=0;
            
            
            
            
        }

    }
                listaVuelos.getbyCodigo(codigoVuelo).getAviondelVuelo().setConfiguracionAsientos2(array);
}
        
    
} 
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCodigo;
    // End of variables declaration//GEN-END:variables
}
